// Book-3/chapter-01/exercise-03-framework-comparison/starter/vue/ProductCard.vue
<template>
  <div class="product-card">
    <img :src="product.image" :alt="product.name">
    <h2>{{ product.name }}</h2>
    <p class="price">${{ product.price }}</p>
    <p class="description">{{ product.description }}</p>

    <!-- TODO: Add quantity selector -->

    <!-- TODO: Display total -->

    <!-- TODO: Add to cart button -->
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';

// TODO: Define props

// TODO: Add quantity state

// TODO: Add computed property for total

// TODO: Add increment, decrement, and addToCart functions
</script>

<style scoped>
/* Add your styles here */
</style>

// Book-3/chapter-01/exercise-03-framework-comparison/starter/angular/product-card.component.ts
import { Component, Input } from '@angular/core';

interface Product {
  id: number;
  name: string;
  price: number;
  image: string;
  description: string;
}

@Component({
  selector: 'app-product-card',
  template: `
    <div class="product-card">
      <!-- TODO: Add image -->
      <!-- TODO: Add product name -->
      <!-- TODO: Add price -->
      <!-- TODO: Add description -->

      <!-- TODO: Add quantity selector -->

      <!-- TODO: Display total -->

      <!-- TODO: Add to cart button -->
    </div>
  `,
  styles: [`
    /* Add your styles here */
  `]
})
export class ProductCardComponent {
  @Input() product!: Product;

  // TODO: Add quantity property

  // TODO: Add getter for total

  // TODO: Add increment method

  // TODO: Add decrement method

  // TODO: Add addToCart method
}
