// Book-3/chapter-01/exercise-03-framework-comparison/starter/react/ProductCard.jsx
import { useState } from 'react';

function ProductCard({ product }) {
  // TODO: Add state for quantity

  // TODO: Calculate total price

  // TODO: Add increment, decrement, and addToCart functions

  return (
    <div className="product-card">
      <img src={product.image} alt={product.name} />
      <h2>{product.name}</h2>
      <p className="price">${product.price}</p>
      <p className="description">{product.description}</p>

      {/* TODO: Add quantity selector */}

      {/* TODO: Display total */}

      {/* TODO: Add to cart button */}
    </div>
  );
}

export default ProductCard;

// Book-3/chapter-01/exercise-03-framework-comparison/starter/vue/ProductCard.vue
<template>
  <div class="product-card">
    <img :src="product.image" :alt="product.name">
    <h2>{{ product.name }}</h2>
    <p class="price">${{ product.price }}</p>
    <p class="description">{{ product.description }}</p>

    <!-- TODO: Add quantity selector -->

    <!-- TODO: Display total -->

    <!-- TODO: Add to cart button -->
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';

// TODO: Define props

// TODO: Add quantity state

// TODO: Add computed property for total

// TODO: Add increment, decrement, and addToCart functions
</script>

<style scoped>
/* Add your styles here */
</style>
